kube-prometheus-stack:
  fullnameOverride: prometheus-stack

  crds:
    enabled: true

  prometheusOperator:
    enabled: true

  prometheus:
    enabled: true
    prometheusSpec:
      retention: 15d
      scrapeInterval: 30s
      evaluationInterval: 30s
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      storageSpec: {}

  alertmanager:
    enabled: true
    alertmanagerSpec:
      storage: {}

  grafana:
    enabled: true
    defaultDashboardsEnabled: true
    service:
      type: ClusterIP
    ingress:
      enabled: false
    persistence:
      enabled: false

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true

  defaultRules:
    create: true
    rules:
      alertmanager: true
      etcd: true
      configReloaders: true
      general: true
      k8s: true
      kubeApiserverAvailability: true
      kubeApiserverBurnrate: true
      kubeApiserverHistogram: true
      kubeApiserverSlos: true
      kubeControllerManager: true
      kubelet: true
      kubeProxy: true
      kubePrometheusGeneral: true
      kubePrometheusNodeRecording: true
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      kubeSchedulerAlerting: true
      kubeSchedulerRecording: true
      kubeStateMetrics: true
      network: true
      node: true
      nodeExporterAlerting: true
      nodeExporterRecording: true
      prometheus: true
      prometheusOperator: true
